### ISSUE TITLE
If you have time, please help me

### ISSUE THREAD

**Issue by nemonamo** [furyhawk/tftchamp#2]
I am "Nemo," a college student studying machine learning in Korea.
I analyzed tft season 7 data with the kaggle link you uploaded and received 7.5 kr data in csv format in riot api this season, but the MDI of the 1cost units is at the top, so I doubt if I did it wrong.
I think it's because I made a mistake in the data preprocessing process.
Any other regional data is fine, but do you have the latest version of the csv file? If you don't mind, can you share it with me?
I will upload the data file that I used. I can apply any advice.
[KR.csv](https://github.com/furyhawk/tftchamp/files/10147914/KR.csv)
![123](https://user-images.githubusercontent.com/96330533/205475796-d57018e9-9fb9-4af4-b216-5f83b1db0d09.PNG)

**Comment by furyhawk** [comment]
I have closed the database for Set7.5. I can provide the csv for Set8 this weekend once there are Master rank players.

**Comment by furyhawk** [comment]
Hi @nemonamo,

Attached is KR master set8 matches, hope it helps. Afraid there is only a few match on day02

[kr_masters_12.23.483.5208_2022-12-07_matches.csv](https://github.com/furyhawk/tftchamp/files/10195893/kr_masters_12.23.483.5208_2022-12-07_matches.csv)

**Comment by nemonamo** [comment]
I really appreciate everything you've done.
